import random
import string

departments = [
    "Accounting",
    "Research",
    "Sales",
    "Operations",
    "Marketing",
    "Human Resources",
]


def generate_random_epoch_between(start: int, end: int) -> int:
    """Generate a random epoch between start and end"""
    return random.randint(start, end)


start_epoch = 1690395957
now_ms_epoch = 1695752819


def create_snowflake_inserts_file(n: int) -> None:
    """Create a file with n snowflake inserts"""
    with open("./sql/snowflake-inserts.sql", "w") as f:
        f.write("-- this script generated by generate-data.py \n")
        f.write("use warehouse whylogs_warehouse; \n")
        f.write("insert into whylogs_demo.public.demo_table(id, name, age, department, dataset_timestamp) values \n")
        for i in range(n):
            random_department = random.choice(departments)
            random_characters = "".join(random.choices(string.ascii_letters, k=10))
            random_age = random.randint(0, 80)
            random_epoch = generate_random_epoch_between(start_epoch, now_ms_epoch)
            f.write(f"({i}, '{random_characters}', {random_age}, '{random_department}', TO_TIMESTAMP_NTZ({random_epoch})) {',' if i < n-1 else ';'} \n")


if __name__ == "__main__":
    create_snowflake_inserts_file(10_000)
