
CREATE OR REPLACE SECRET whylabs_api_key
  TYPE = GENERIC_STRING
  SECRET_STRING = '3rXyFtxHnj.uOShmZhh0aVfeIyCXVdZf263emrmZwXkZ9crrkW9OeVnVu0qxWu6K';

CREATE OR REPLACE SECRET whylabs_org_id
  TYPE = GENERIC_STRING
  SECRET_STRING = 'org-JpsdM6';

CREATE OR REPLACE SECRET whylabs_dataset_id
  TYPE = GENERIC_STRING
  SECRET_STRING = 'model-73';

CREATE OR REPLACE SECRET segment_columns
  TYPE = GENERIC_STRING
  SECRET_STRING = 'STATE'; -- Must be all caps

CREATE OR REPLACE SECRET data_grouper_freq
  TYPE = GENERIC_STRING
  SECRET_STRING = 'D';
